name: pages - build and deploy docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        
      - name: Build Jekyll (.md)
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./doc
          destination: ./_site


      - name: Build Pandoc (.tex)
        run: |
          pandoc --toc -s --mathjax doc/tut.tex -o ./_site/tut.html
          pandoc --toc -s --mathjax doc/mod.tex -o ./_site/mod.html

      # Upload combined site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5